version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3000"
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
